// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGngJIrxlGxiULzq1a5ZH2O4NaM_Ojt2I',
    appId: '1:624815648508:web:d2f671a5dd0755a90cb179',
    messagingSenderId: '624815648508',
    projectId: 'apophenia-1c2a1',
    authDomain: 'apophenia-1c2a1.firebaseapp.com',
    storageBucket: 'apophenia-1c2a1.firebasestorage.app',
    measurementId: 'G-T9Y2J7NEBE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAgw5ABSsj6zECPu8Vh64CBW2lSoIZJsw',
    appId: '1:624815648508:android:55d7952255e3dea90cb179',
    messagingSenderId: '624815648508',
    projectId: 'apophenia-1c2a1',
    storageBucket: 'apophenia-1c2a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9OAuNe5p8eCzrxZBHaBNKAJs_jtQYn9I',
    appId: '1:624815648508:ios:3965c1b6aa243f8d0cb179',
    messagingSenderId: '624815648508',
    projectId: 'apophenia-1c2a1',
    storageBucket: 'apophenia-1c2a1.firebasestorage.app',
    iosBundleId: 'com.alfaresi.apophenia',
  );

}